# -*- coding: utf-8 -*-
"""problem_9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p6SwMSjqBCsNk1hZlbqnwdJCOVpEZzBS
"""

import numpy as np

def ModifiedQR(A,x):
  for i in range(1000):
    sigma = A[A.shape[0]-1][A.shape[0]-1]
    B = A - (sigma*np.identity(A.shape[0]))
    Q,R = np.linalg.qr(B)
    A = np.matmul(R,Q) + sigma*np.identity(A.shape[0])
  return A

# A,x from Problem 6
A = np.array([[2,3,2],[10,3,4],[3,6,1]])
x = np.array([[0,0,1]])
x = x.T
print("Result For Problem 6 :- ")
print(ModifiedQR(A,x))

print("\n")

# A,x from Problem 7
A = np.array([[6,2,1],[2,3,1],[1,1,1]])
x = np.array([[0,0,1]])
x = x.T
print("Result For Problem 7 :- ")
print(ModifiedQR(A,x))