# -*- coding: utf-8 -*-
"""problem_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0cCbayMEyjWV8y1CstSOJrpAYsR95sH
"""

import numpy as np

def ShiftedInverse(A,x):
  alpha = 2
  B = A-(alpha*np.identity(A.shape[0]))
  a = 0
  for i in range(5000):
    y = np.linalg.solve(B,x)
    a = abs(y).max(axis = 0)
    x = y/a

  return (1/a + alpha),x
A = np.array([[6,2,1],[2,3,1],[1,1,1]])
x = np.array([[0,1,1]])
x = x.T
eigenvalue,eigenvector = ShiftedInverse(A,x)
print("Eigenvalue :- ")
print(eigenvalue)
print("Eigenvector :- ")
print(eigenvector)
print(np.linalg.eigh(A))