# -*- coding: utf-8 -*-
"""problem_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQ9_AZdQEdSB6cB5oDdPBO3M0q9jbJ-K
"""

import numpy as np

def max_eigenval(A,x):
  prev = 0
  while True:
    x = np.matmul(A,x)
    a = abs(x).max(axis = 0)
    x = x/a
    if(prev == a):
      break
    prev = a
  return prev,x

def min_eigenval(A,x):
  prev = 0
  for i in range(500):
    y = np.linalg.solve(A,x)
    a = abs(y).max(axis=0)
    x = y/abs(a)
    prev = a
  return 1/prev,x

A = np.array([[2,3,2],[10,3,4],[3,6,1]])
x = np.array([[0,0,1]])
x = x.T
eigenvalue,eigenvector = max_eigenval(A,x)
print("Eigenvalue :- ")
print(eigenvalue)
print("Eigenvector :- ")
print(eigenvector)
eigenvalue,eigenvector = min_eigenval(A,x)
print("Eigenvalue :- ")
print(eigenvalue)
print("Eigenvector :- ")
print(eigenvector)
print("Result from np.linalg.eig()")
arr1,arr2 = np.linalg.eig(A)
print(arr1)
print(arr2)